# Generated by Django 3.1.4 on 2021-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='img',
            field=models.ImageField(upload_to='portfolioapp/images/'),
        ),
    ]
