# Generated by Django 3.1.4 on 2021-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20210202_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
            ],
        ),
    ]
